sudo: false
branches:
  only:
    - master
language: nodejs
node_js:
    - 12
install:
    - yarn
jobs:
    include:
        - stage: Build
          name: Upload dist to CDN
          script:
            - yarn build
            - cd dist
            - tar -cvf neditor.tar ./ && xz -z9 neditor.tar
            #- sh -c "curl -T neditor.tar.xz http://v0.api.upyun.com/notadd/download/neditor/Neditor-next-master.tar.xz -u "$UPYUN" -v;  fi"
            #- echo "demo.neditor.notadd.com" > CNAME
deploy:
    provider: pages
    repo: notadd/neditor
    skip-cleanup: true
    github-token: $GITHUB_PUBLISH_TOKEN
    keep-history: true
    local-dir: ./dist
    target-branch: gh-pages
    name: Notadd Bot
    verbose: true
    on:
        repo: notadd/neditor
        branch: master
